### PR TITLE
new test theme

### PR DESCRIPTION
**Pull request by dhyeythumar**
Testing theme preview generation on comments for PRs

### CODE REVIEW

**Comment by dhyeythumar** [comment]
Theme preview generator
            
            
title-color: <code>#00bbff</code>
            
icon-color: <code>#2ddaaa</code>
            
text-color: <code>#ffffff</code>
            
bg-color: <code>#050f2c</code>
      
            
[](https://youtube-stats-card.vercel.app/api?channelid=UCpKizIKSk8ga_LCI3e3GUig&title_color=00bbff&icon_color=2ddaaa&text_color=ffffff&bg_color=050f2c)

**Comment by dhyeythumar** [comment]
Theme preview generator
            
            
title-color: <code>#00bbff</code>
            
icon-color: <code>#2ddaaa</code>
            
text-color: <code>#ffffff</code>
            
bg-color: <code>#050f2c</code>
      
            
[](https://youtube-stats-card.vercel.app/api?channelid=UCpKizIKSk8ga_LCI3e3GUig&title_color=00bbff&icon_color=2ddaaa&text_color=ffffff&bg_color=050f2c)

**Comment by dhyeythumar** [comment]
Theme preview generator
            
            
title-color: <code>#00bbff</code>
            
icon-color: <code>#2ddaaa</code>
            
text-color: <code>#ffffff</code>
            
bg-color: <code>#050f2c</code>
      
            
[](https://youtube-stats-card.vercel.app/api?channelid=UCpKizIKSk8ga_LCI3e3GUig&title_color=00bbff&icon_color=2ddaaa&text_color=ffffff&bg_color=050f2c)

**Comment by dhyeythumar** [comment]
New theme preview in comments is working properly, so closing this PR.

**Comment by VatsalSy** [comment]
Theme preview generator
            
            
title-color: <code>#00bbff</code>
            
icon-color: <code>#2ddaaa</code>
            
text-color: <code>#ffffff</code>
            
bg-color: <code>#050f2c</code>
      
            
[](https://youtube-stats-card.vercel.app/api?channelid=UCpKizIKSk8ga_LCI3e3GUig&title_color=00bbff&icon_color=2ddaaa&text_color=ffffff&bg_color=050f2c)

**Pull request closed without merging**
